config/routes.rb
Blog::Application.routes.draw do
  resources :blog_entries do
    collection do
      get 'tag'
    end
  end

end

app/models/blog_entry.rb
class BlogEntry < ActiveRecord::Base
  acts_as_taggable_on :speed, :topic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/blog_entries_controller.rb
class BlogEntriesController < ApplicationController
  # GET /blog_entries
  # GET /blog_entries.json
  def index
    @speed_tags = BlogEntry.tag_counts_on(:speed)
    @topic_tags = BlogEntry.tag_counts_on(:topic)
    @blog_entries = BlogEntry.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @blog_entries }
    end
  end

  def tag
    @speed_tags = BlogEntry.tag_counts_on(:speed)
    @topic_tags = BlogEntry.tag_counts_on(:topic)
    @blog_entries = BlogEntry.tagged_with(params[:id])
    render :index
  end

  # GET /blog_entries/1
  # GET /blog_entries/1.json
  def show
    @blog_entry = BlogEntry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @blog_entry }
    end
  end

  # GET /blog_entries/new
  # GET /blog_entries/new.json
  def new
    @blog_entry = BlogEntry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @blog_entry }
    end
  end

  # GET /blog_entries/1/edit
  def edit
    @blog_entry = BlogEntry.find(params[:id])
  end

  # POST /blog_entries
  # POST /blog_entries.json
  def create
    @blog_entry = BlogEntry.new(params[:blog_entry])

    respond_to do |format|
      if @blog_entry.save
        format.html { redirect_to @blog_entry, :notice => 'Blog entry was successfully created.' }
        format.json { render :json => @blog_entry, :status => :created, :location => @blog_entry }
      else
        format.html { render :action => "new" }
        format.json { render :json => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /blog_entries/1
  # PUT /blog_entries/1.json
  def update
    @blog_entry = BlogEntry.find(params[:id])

    respond_to do |format|
      if @blog_entry.update_attributes(params[:blog_entry])
        format.html { redirect_to @blog_entry, :notice => 'Blog entry was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @blog_entry.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_entries/1
  # DELETE /blog_entries/1.json
  def destroy
    @blog_entry = BlogEntry.find(params[:id])
    @blog_entry.destroy

    respond_to do |format|
      format.html { redirect_to blog_entries_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_entries_helper.rb
module BlogEntriesHelper
  include ActsAsTaggableOn::TagsHelper
end

app/views/blog_entries/_blog_entry.html.erb
<div id="welcome" class="post">
	<h2 class="title"><%= blog_entry.title %></h2>
	<h3 class="date"><span class="month"><%= blog_entry.created_at.month %></span> <span class="day"> <%= blog_entry.created_at.day %></span><span class="year"> <%= blog_entry.created_at.year %></span></h3>
	<div class="story">
		<p><%= blog_entry.description %></p>
	</div>
</div>

app/views/blog_entries/_blog_entry_preview.html.erb
<li>
	<h3><%= blog_entry_preview.created_at %></h3>
	<p><a href="#"><%= blog_entry_preview.description.first 20 %></a></p>
</li>

app/views/blog_entries/_form.html.erb
<%= form_for(@blog_entry) do |f| %>
  <% if @blog_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_entry.errors.count, "error") %> prohibited this blog_entry from being saved:</h2>

      <ul>
      <% @blog_entry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label 'Read Time' %><br />
    <%= f.text_field :speed_list %>
  </div>
  <div class="field">
    <%= f.label 'Topic' %><br />
    <%= f.text_field :topic_list %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blog_entries/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_entry %> |
<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/index.html.erb
<h1>Listing Blog</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @blog_entries.each do |blog_entry| %>
  <tr>
    <td><%= blog_entry.title %></td>
    <td><%= blog_entry.description.first 15 %></td>
    <td><%= link_to 'Show', blog_entry %></td>
    <td><%= link_to 'Edit', edit_blog_entry_path(blog_entry) %></td>
    <td><%= link_to 'Destroy', blog_entry, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<p>
  <% tag_cloud(@speed_tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
  <% end %>
</p>

<p>
  <% tag_cloud(@topic_tags, %w(css1 css2 css3 css4)) do |tag, css_class| %>
    <%= link_to tag.name, { :action => :tag, :id => tag.name }, :class => css_class %>
  <% end %>
</p>

<% if params[:action] == 'tag' %>
  <p><%= link_to 'Show all Blog Entries', blog_entries_path %></p>
<% end %>

<%= link_to 'New Blog entry', new_blog_entry_path %>

app/views/blog_entries/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_entries_path %>

app/views/blog_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @blog_entry.title %>
</p>

<p>
  <b>Description:</b>
  <%= @blog_entry.description %>
</p>

<p>
  <b>How fast can be read:</b>
  <%= @blog_entry.speed_list %>
</p>

<p>
  <b>The topics of the blog post:</b>
  <%= @blog_entry.topic_list %>
</p>


<%= link_to 'Edit', edit_blog_entry_path(@blog_entry) %> |
<%= link_to 'Back', blog_entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/blog_entries.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<!--
Design by Free CSS Templates
http://www.freecsstemplates.org
Released for free under a Creative Commons Attribution 2.5 License
-->
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>Midnight by Free Css Templates</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<%= stylesheet_link_tag    "default" %>
<%= csrf_meta_tags %>

</head>
<body>
<div id="header">
	<div id="logo">
		<h1><a href="#">Midnight</a></h1>
		<h2><a href="http://www.freecsstemplates.org/">By Free CSS Templates</a></h2>
	</div>
	<div id="menu">
		<ul>
			<li class="active"><a href="#" title="">Homepage</a></li>
			<li><a href="#" title="">About Us</a></li>
			<li><a href="#" title="">Products</a></li>
			<li><a href="#" title="">Clients</a></li>
			<li><a href="#" title="">Support</a></li>
		</ul>
	</div>
</div>
<div id="wrapper">
	<div id="content">
		<div id="sidebar">
			<div id="support">
				<h2>Customer Support</h2>
				<h3>1-800-1234567</h3>
			</div>
			<div id="login" class="boxed">
				<h2 class="title">Client Account</h2>
				<div class="content">
					<form id="form1" method="post" action="#">
						<fieldset>
						<legend>Sign-In</legend>
						<label for="inputtext1">Client ID:</label>
						<input id="inputtext1" type="text" name="inputtext1" value="" />
						<label for="inputtext2">Password:</label>
						<input id="inputtext2" type="password" name="inputtext2" value="" />
						<input id="inputsubmit1" type="submit" name="inputsubmit1" value="Sign In" />
						<p><a href="#">Forgot your password?</a></p>
						</fieldset>
					</form>
				</div>
			</div>
			<div id="updates" class="boxed">
				<h2 class="title">Recent Updates</h2>
				<div class="content">
					<ul>
					  <%= render :partial => "blog_entry_preview", :collection => @blog_entries %>
					</ul>
				</div>
			</div>
		</div>
		<div id="main">
		  <%= render @blog_entries %>
		</div>
	</div>
	<div style="clear: both;">&nbsp;</div>
</div>
<div id="footer">
	<p id="legal">Copyright &copy; 2007 Midnight. All Rights Reserved. Designed by <a href="http://www.freecsstemplates.org/">Free CSS Templates</a>.</p>
	<p id="links"><a href="#">Privacy Policy</a> | <a href="#">Terms of Use</a></p>
</div>
</body>
</html>